# The URL the site will be built for
base_url = "https://rajivharlalka.tech"

title = "Rajiv"
description = "Minimalism | Pensive | Tennis"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme="accio"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_feed=true

taxonomies = [
    {name = "categories", rss = true},   
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
highlight_theme="material-dark"

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
# Put all your custom variables here
author= "Rajiv"
blog_menu = [
    {url = "$BASE_URL/about", name = "About Me"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "https://notes.rajivharlalka.tech", name = "Notes"},
    {url="$BASE_URL/Resume.pdf",name="Resume"}
]
GITHUB_USERNAME="rajivharlalka"